services:
  attacker_system:
    image: dc3lik/attacker_system:latest
    container_name: attacker_system
    hostname: attacker_system
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - dc_network
    ports:
      - "127.0.0.1:10022:22"
      
  target_recon:
    image: dc3lik/target_recon:latest
    container_name: target_recon
    hostname: target_recon
    networks:
      - dc_network
      
networks:
  dc_network:
    driver: bridge
